PowerCoWebSite/Controllers/AuthController.cs
using PowerCoWebSite.ViewModels;
using System.Web.Mvc;
using System.Web.Security;

namespace PowerCoWebSite.Controllers
{
    public class AuthController : Controller
    {
        // GET: Auth
        public ActionResult Login()
        {
            return View(new LoginViewModel{});
        }

        [HttpPost]
        public ActionResult Login(LoginViewModel form, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                // if user is not in database then notify user that he entered wrong password or user name
                if (!form.IsUserExists())
                {
                    ModelState.AddModelError("LoginError", "The user name or password provided is incorrect.");
                }
                else
                {
                    // authenticate user and add him to the coockies collection. Keep user loged in
                    FormsAuthentication.SetAuthCookie(form.Name, true);

                    //Redirect user to main page
                    return RedirectToAction("Index", "MainPage");
                }
            }

            // If we got this far, something failed, redisplay form
            return View(form);
        }

        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "MainPage");
        }
    }
}

PowerCoWebSite/Controllers/EmployeeManagementController.cs
using PowerCoWebSite.ViewModels;
using System.Web.Mvc;

namespace PowerCoWebSite.Controllers
{
    public class EmployeeManagementController : Controller
    {
        // GET: EmployeeManagment
        public ActionResult EmployeesManagementIndex()
        {
            if (User.IsInRole("Admin"))
            {
                EmployeesViewModel evm = new EmployeesViewModel();

                return View(evm);
            }

            return RedirectToAction("Index", "MainPage");
        }

        public ActionResult NewEmployee()
        {
            if (User.IsInRole("Admin"))
            {
                return View(new NewEmployeeViewModel());
            }

            return RedirectToAction("Index", "MainPage");
        }

        [HttpPost]
        public ActionResult NewEmployee(NewEmployeeViewModel form)
        {
            if (!ModelState.IsValid)
                return View(form);

            form.AddEmployee();

            return RedirectToAction("EmployeesManagementIndex");
        }

        public ActionResult EditEmployee(int id)
        {
            if (User.IsInRole("Admin"))
            {
                EditEmployeeViewModel evm = new EditEmployeeViewModel();
                evm.GetEmployee(id);
                evm.SetDropDownListCurrentItems();

                return View(evm);
            }

            return RedirectToAction("Index", "MainPage");
        }

        [HttpPost]
        public ActionResult EditEmployee(int id, EditEmployeeViewModel form)
        {
            if (!ModelState.IsValid)
                return View(form);

            form.ModifyEmployee(id);

            return RedirectToAction("EmployeesManagementIndex");
        }

        [HttpPost]
        public ActionResult DeleteEmployee(int id)
        {
            EditEmployeeViewModel evm = new EditEmployeeViewModel();
            evm.RemoveEmployee(id);
            return RedirectToAction("EmployeesManagementIndex");
        }
    }
}

PowerCoWebSite/Views/Shared/_Layout.cshtml
@using System.Web.Optimization

@{
    Layout = null;
}


<head>
    <meta name="viewport" content="width=device-width" />
    <title>MainPage</title>
    <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js"></script>
    @Styles.Render("~/styles")
    @Scripts.Render("~/scripts")
</head>

<nav>
    <ul id="nav">
        <li>
            @Html.ActionLink("POWERCO", "Index", "MainPage")
        </li>
        <li>
            @Html.ActionLink("Company", "Company", "MainPage")
            <ul>
                <li>@Html.ActionLink("About", "About", "MainPage")</li>
                <li>@Html.ActionLink("Our Team", "Team", "MainPage")</li>
            </ul>
        </li>
        <li>
            @Html.ActionLink("Contacts", "Contacts", "MainPage")
            <ul>
                <li>@Html.ActionLink("Our Office", "Contacts", "MainPage")</li>
            </ul>
        </li>
        <li>
            @if (User.IsInRole("Admin"))
            {
                @Html.ActionLink("EMS", "EmployeesManagementIndex", "EmployeeManagement")
            }
        </li>
        <li class="mpull-right">
            @if (User.Identity.IsAuthenticated)
            {
                @Html.ActionLink("Logout", "Logout", "Auth")
            }
            else
            {
                @Html.ActionLink("Register", "Register", "MainPage")
            }
        </li>

        <li class="mpull-right">
            @if (User.Identity.IsAuthenticated)
            {
                <a> Welcome, @User.Identity.Name </a>
            }
            else
            {
                @Html.ActionLink("Login", "Login", "Auth")
            }
        </li>

    </ul>
</nav>

<body style="background-image:url(http://citycelebrity.ru/userfiles/DSC_3138.jpg); background-size:cover;">
    <div id="bodycontainer">

        @RenderBody()

    </div>

    <div id="modal-container" class="modal fade" tabindex="-1" role="dialog">
        <div class="modal-content mymodalcont">
        </div>
    </div>

    @RenderSection("Scripts", false)

</body>

<div style="background-color:black; width:100%; height:200px;">
    <div style="width: 100%; float: left; padding: 0px 150px 0 150px">
        <div style="float: left; width: 25%;">
            <div style="margin: 10px; padding: 10px; padding-bottom:0">
                <h4 style="color:goldenrod; text-align:center">Headquarters</h4>
                <p style="color:goldenrod; text-align:center">7304 Bridgeton Ave.</p>
                <p style="color:goldenrod; text-align:center">Philadelphia</p>
                <p style="color:goldenrod; text-align:center">PA 19111</p>
            </div>
        </div>
        <div style="float: left; width: 25%;">
            <div style="margin: 10px; padding: 10px; padding-bottom:0">
                <h4 style="color:goldenrod; text-align:center">Company</h4>
                <p style="text-align:center">@Html.ActionLink("About", "About", "MainPage", new { @style = "color:goldenrod" })</p>
                <p style="text-align:center">@Html.ActionLink("Our Team", "Team", "MainPage", new { @style = "color:goldenrod" })</p>
            </div>
        </div>
        <div style="float: left; width: 25%; ">
            <div style="margin: 10px; padding: 10px; padding-bottom:0">
                <h4 style="color:goldenrod; text-align:center">Contacts</h4>
                <p style="text-align:center">@Html.ActionLink("Our Office", "Contacts", "MainPage", new { @style = "color:goldenrod" })</p>
                <p style="text-align:center">@Html.ActionLink("Contact Us", "ContactUs", "MainPage", new { @style = "color:goldenrod" })</p>
            </div>
        </div>
        <div style="float: left; width: 25%;">
            <div style="margin: 10px; padding: 10px; padding-bottom:0">
                <a href="https://www.linkedin.com/">
                    <span class="fa-stack fa-lg">
                        <i class="fa fa-square fa-stack-2x" style="color:white"></i>
                        <i class="fa fa-facebook fa-stack-1x" style="color:goldenrod"></i>
                    </span>
                </a>
                <a href="https://www.linkedin.com/">
                    <span class="fa-stack fa-lg">
                        <i class="fa fa-square fa-stack-2x" style="color:white"></i>
                        <i class="fa fa-linkedin fa-stack-1x" style="color:goldenrod"></i>
                    </span>
                </a>
                <a href="https://www.linkedin.com/">
                    <span class="fa-stack fa-lg">
                        <i class="fa fa-square fa-stack-2x" style="color:white"></i>
                        <i class="fa fa-twitter fa-stack-1x" style="color:goldenrod"></i>
                    </span>
                </a>
                <a href="https://www.linkedin.com/">
                    <span class="fa-stack fa-lg">
                        <i class="fa fa-square fa-stack-2x" style="color:white"></i>
                        <i class="fa fa-google-plus fa-stack-1x" style="color:goldenrod"></i>
                    </span>
                </a>
                <a href="https://www.linkedin.com/">
                    <span class="fa-stack fa-lg">
                        <i class="fa fa-square fa-stack-2x" style="color:white"></i>
                        <i class="fa fa-vk fa-stack-1x" style="color:goldenrod"></i>
                    </span>
                </a>
            </div>
        </div>
    </div>
    <div style="clear: both;"></div>
    <div style="color:white; text-align: center">
        © 2016 Globalize
    </div>
</div>